// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6e92fc_Hd6DdZjHAF_YQ7oL5-X-kYVcA',
    appId: '1:285461318727:web:eb3d9b506dc706b2d0f562',
    messagingSenderId: '285461318727',
    projectId: 'chateo-2aaee',
    authDomain: 'chateo-2aaee.firebaseapp.com',
    storageBucket: 'chateo-2aaee.appspot.com',
    measurementId: 'G-PQ8RXGKYZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTMG9hJnmA_EbMzJpBPczpmrAUMgTWRM',
    appId: '1:285461318727:android:7e7ee3500e486616d0f562',
    messagingSenderId: '285461318727',
    projectId: 'chateo-2aaee',
    storageBucket: 'chateo-2aaee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMw2cANWRCjATiewJSMPA3WunRulX6Hfc',
    appId: '1:285461318727:ios:212b9d960b66175cd0f562',
    messagingSenderId: '285461318727',
    projectId: 'chateo-2aaee',
    storageBucket: 'chateo-2aaee.appspot.com',
    iosBundleId: 'com.example.chateoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMw2cANWRCjATiewJSMPA3WunRulX6Hfc',
    appId: '1:285461318727:ios:c58f5e93afd56c7bd0f562',
    messagingSenderId: '285461318727',
    projectId: 'chateo-2aaee',
    storageBucket: 'chateo-2aaee.appspot.com',
    iosBundleId: 'com.example.chateoApp.RunnerTests',
  );
}
